import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          <div className='nav-item'>
            Home
          </div>
          <div className='nav-item'>
            About
          </div>
          <div className='nav-item'>
            Projects
          </div>
        </div>
        {children}
        </body>
    </html>
  )
}
